### ISSUE TITLE
CamundaBpmDataBuilder should not fail when setting null values.

### ISSUE THREAD

**Issue by jangalinski** [holunda-io/camunda-bpm-data#46]
Use Case:

I receive some simple pojo  (say Customer) and want to build a VariableMap from it to pass to camunda.

I do:

```
VariableMap variables = CamundaBpmData.builder().set(MY_DECLARED_CUSTOMER_NAME_VF, customer.getName()).build();
```

if the customer.getName() returns null, i get:

```
java.lang.NullPointerException
	at io.holunda.camunda.bpm.data.adapter.ValueWrapperUtil.getTypedValue(ValueWrapperUtil.java:42)
	at io.holunda.camunda.bpm.data.adapter.basic.AbstractBasicReadWriteAdapter.getTypedValue(AbstractBasicReadWriteAdapter.java:48)
	at io.holunda.camunda.bpm.data.adapter.basic.ReadWriteAdapterVariableMap.set(ReadWriteAdapterVariableMap.java:35)
      ....
```

**Comment by jangalinski** [comment]
I guess the fix is to do the Illegal ArgumentException check only if the value is not null here:

      if (!clazz.isAssignableFrom(value.getClass())) {
            throw new IllegalArgumentException("Couldn't create TypedValue for " + clazz.getSimpleName() + " from value " + value);}

**Comment by jangalinski** [comment]
If approved I would like to see this released asap, arbitrary of the ACL and Json/Spin features.
